#!/usr/bin/env bash
# This script parses the /etc/passwd file

FILE="/etc/passwd"

while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do
	# Print the user's name, group, and home directory
	printf "The user %s is part of the %s gang, lives in %s and rides " "$f1" "$f4" "$f6"

	# Print the user's password, full name, and additional information
	printf "%s. %s's place is protected by the passcode %s, more info about the user here:" "$f7" "$f3" "$f2"
	printf " %s" "$f5"

	printf "\n"
done < "$FILE"

exit 0
