#!/usr/bin/env bash
# Script to print `Best School` 10 times using a while loop.

# Initialize `pass` variable
PASS=0

while [ "$PASS" -lt 10 ]
do
	# Print `Hi` on a 9th pass.
	if [ "$PASS" -eq 8 ]
	then
		echo -e "Best School\nHi"
	else
		echo "Best School"
	fi

	# Increment number of passes.
	((PASS++))
done

exit 0
