#!/usr/bin/env bash
# Script that checks information about the `school` file.

# define filename
FILE="school"

# Check if file exists
if [ -e $FILE ]
then
	echo "$FILE file exists"

	# Check if file is not empty
	if [ -s $FILE ]
	then
		echo "$FILE file is not empty"
	else
		echo "$FILE file is empty"
	fi

	# Check if file is regular file
	if [ -f $FILE ]
	then
		echo "$FILE is a regular file"
	fi
else
	echo "$FILE file does not exist"
fi
