#!/usr/bin/env bash
# Appends a public ssh key to authorized file.
# Save the public key you want to append in ssh_key.pub file
#+Pass it as argument to the script.

# Check if user is running as root
if [[ $EUID -ne 0 ]]; then
	echo "Run this script using sudo"
	exit 1
fi

# Check if public key is not passed.
if [[ $# -ne 1 ]]; then
	echo "Usage: $0 <ssh_key.pub file>"
	exit 1
fi

# Define the path to the public key file and authorized_keys file
PUBLIC_KEY_FILE="$1"
AUTHORIZED_KEYS_FILE="$(eval echo ~"$SUDO_USER")/.ssh/authorized_keys"

# Check if the public key already exists in authorized_keys
if grep -q "$(cat "$PUBLIC_KEY_FILE")" "$AUTHORIZED_KEYS_FILE"; then
  echo "Public key already exists in $AUTHORIZED_KEYS_FILE. Skipping."
else
  # Append the public key to the authorized_keys file
  cat "$PUBLIC_KEY_FILE" >> "$AUTHORIZED_KEYS_FILE"
  echo "Public key appended to $AUTHORIZED_KEYS_FILE."
fi

