#!/usr/bin/env bash
# Configures an Ubuntu server with the below requirements.
# `localhost` resolves to `127.0.02`
# `facebook.com` resolves to `8.8.8.8`.

# Copy file to home directory to modify it.
cp /etc/hosts ~/hosts.new

# Modify the hosts using echo command.
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new

# Copy bach the file, -f to replace existing file.
cp -f ~/hosts.new /etc/hosts
