#!/usr/bin/env bash
# Connects to localhost on port 98 using telnet.

# Check if user is root
if [[ $EUID -ne 0 ]]
then
	echo "This script must be run as root"
	exit 1
fi

# Use netcat command to start listening
nc -l 98
